version: '3.8'
services:
  db:
     image: mysql:8.0
     container_name: db
     volumes:
       - ./:/docker-entrypoint-initdb.d/
     restart: always
     ports:
       - 3307:3306
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: task
       MYSQL_USER: user
       MYSQL_PASSWORD: user
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8091:80
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8090:8080

